name: CI Build and Test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * 1-6"   # 17:00 UTC = 9:00 PST, Monday to Friday
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        bash install_chrome.sh

    - name: Run tests
      run: |
        python rate4.py > output.log 2>&1

    - name: Commit workflow output
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config user.name "github-actions[botlol]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        mkdir -p logs
        mv output.log logs/output-$(date +"%Y%m%d-%H%M%S").log
        git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/yinshiyi/epic.git
        git fetch origin workflow-logs
        git checkout workflow-logs
        git add logs/
        git commit -m "Add workflow output log $(date +"%Y-%m-%d %H:%M:%S")" || echo "No changes to commit"
        # Force Git to use PAT
        git push origin workflow-logs
