name: CI Build and Test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * 1-6"   # 17:00 UTC = 9:00 PST, Monday to Friday
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        bash install_chrome.sh

    - name: Run tests
      run: |
        python rate4.py > output.log 2>&1

    - name: Upload test output
      uses: actions/upload-artifact@v4
      with:
        name: test-output
        path: output.log